### ISSUE TITLE
之前一直可以，今天报错，已经更新cookie

### ISSUE THREAD

**Issue by qiyuan-chen** [Tomtao626/GLaDOS_Checkin#8]
```shell
Run python3 ./glados/main.py --cookie_string "***"
【Account_1】:
Traceback (most recent call last):
  File "./glados/main.py", line 37, in <module>
    checkin_code, message = glados(cookie)
  File "D:\a\GLaDOS_Checkin\GLaDOS_Checkin\glados\glados.py", line 74, in glados
    driver = uc.Chrome(version_main=version, options=options)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\undetected_chromedriver\__init__.py", line 247, in __init__
    self.patcher.auto()
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\undetected_chromedriver\patcher.py", line [15](https://github.com/qiyuan-chen/GLaDOS_Checkin/actions/runs/5681033510/job/15396314469#step:4:16)8, in auto
    release = self.fetch_release_number()
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\undetected_chromedriver\patcher.py", line [22](https://github.com/qiyuan-chen/GLaDOS_Checkin/actions/runs/5681033510/job/15396314469#step:4:23)2, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 5[31](https://github.com/qiyuan-chen/GLaDOS_Checkin/actions/runs/5681033510/job/15396314469#step:4:32), in open
    response = meth(req, response)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Error: Process completed with exit code 1.
```

**Comment by zju-ch** [comment]
一样

**Comment by Daxifen** [comment]
我也出现了同样的问题

**Comment by zlfengshare** [comment]
同样问题

**Comment by jiarui666** [comment]
顶

**Comment by xuexiji** [comment]
修改一下`glados.py`，将`'{"token": "glados.network"}'`修改为`'{"token": "glados.one"}'`，应该就可以了

**Comment by realmrnoname** [comment]
应该是官方该东西了吧，老哥什么时候修

**Comment by realmrnoname** [comment]
> 修改一下`glados.py`，将`'{"token": "glados.network"}'`修改为`'{"token": "glados.one"}'`，应该就可以了

不行，还是同样的报错

**Comment by Blackyu-he** [comment]
一样问题，我之前用的另一个仓库也是404错误

**Comment by wdssfff00** [comment]
所有glados的链接改成glados.one

**Comment by Blackyu-he** [comment]
我全部改成glados.one了，还是不行
![image](https://github.com/Tomtao626/GLaDOS_Checkin/assets/66365398/00d08b9c-ee77-465f-bdbf-19aed8efb410)
``` py
Run python3 ./glados/main.py --cookie_string "***
【Account_1】:
Traceback (most recent call last):
  File "./glados/main.py", line 37, in <module>
    checkin_code, message = glados(cookie)
  File "D:\a\GLaDOS_Checkin\GLaDOS_Checkin\glados\glados.py", line 74, in glados
    driver = uc.Chrome(version_main=version, options=options)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\undetected_chromedriver\__init__.py", line 247, in __init__
    self.patcher.auto()
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\undetected_chromedriver\patcher.py", line [15](https://github.com/Blackyu-he/GLaDOS_Checkin/actions/runs/5692744970/job/15430372420#step:4:16)8, in auto
    release = self.fetch_release_number()
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\undetected_chromedriver\patcher.py", line [22](https://github.com/Blackyu-he/GLaDOS_Checkin/actions/runs/5692744970/job/15430372420#step:4:23)2, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 5[31](https://github.com/Blackyu-he/GLaDOS_Checkin/actions/runs/5692744970/job/15430372420#step:4:32), in open
    response = meth(req, response)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Error: Process completed with exit code 1.
```

**Comment by qingyanmaodai** [comment]
+1

**Comment by lg-yyds** [comment]
{"token": "glados.network"}不行

**Comment by javakam** [comment]
👍 PR11 是可以的  #11 ；<https://github.com/Tomtao626/GLaDOS_Checkin/pull/11/files>

![image](https://github.com/Tomtao626/GLaDOS_Checkin/assets/15343661/d59080c4-9b1c-48c4-80de-edcf2e1d249b)
